# This contain tasks to configure CLOS Spine switches wth BGP and further show it
---
- name: Replace common Clos BGP CLI command template with spine values
  template: src=clos_spine_bgp_common.j2 dest=./commands/clos_spine_bgp_{{ inventory_hostname }}_commands.txt
  with_items: "{{clos_spine_bgp_common_data}}"

- name: Applying common Clos BGP CLI commands to all spine switches
  cnos_template: host={{inventory_hostname}} username={{ hostvars[inventory_hostname]['username']}}  password={{ hostvars[inventory_hostname]['password']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} commandfile=./commands/clos_spine_bgp_{{ inventory_hostname }}_commands.txt outputfile=./results/clos_spine_bgp_command_{{ inventory_hostname }}_output.txt

  
- name: Replace unique Clos BGP CLI command template with unique spine values for SP21
  template: src=clos_spine_bgp_unique.j2 dest=./commands/clos_unique_spine_bgp_{{ inventory_hostname }}_clos_spine_bgp_SP21_data_commands.txt
  with_items: "{{clos_spine_bgp_SP21_data}}"

- name: Replace unique Clos BGP CLI command template with unique spine values for SP22
  template: src=clos_spine_bgp_unique.j2 dest=./commands/clos_unique_spine_bgp_{{ inventory_hostname }}_clos_spine_bgp_SP22_data_commands.txt
  with_items: "{{clos_spine_bgp_SP22_data}}"

- name: Applying unique Clos BGP CLI commands to SP21 switch
  cnos_conditional_template: host={{inventory_hostname}} commandfile=./commands/clos_unique_spine_bgp_{{ inventory_hostname }}_clos_spine_bgp_SP21_data_commands.txt username={{ hostvars[inventory_hostname]['username']}} password={{ hostvars[inventory_hostname]['password']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} condition={{ hostvars[inventory_hostname]['condition']}} flag='{{item.flag}}' outputfile=./results/clos_unique_spine_bgp_command_{{ inventory_hostname }}_clos_spine_bgp_SP21_data_output.txt
  with_items: "{{clos_spine_bgp_SP21_data}}"
  
- name: Applying unique Clos BGP CLI commands to SP22 switch
  cnos_conditional_template: host={{inventory_hostname}} commandfile=./commands/clos_unique_spine_bgp_{{ inventory_hostname }}_clos_spine_bgp_SP22_data_commands.txt username={{ hostvars[inventory_hostname]['username']}} password={{ hostvars[inventory_hostname]['password']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} condition={{ hostvars[inventory_hostname]['condition']}} flag='{{item.flag}}' outputfile=./results/clos_unique_spine_bgp_command_{{ inventory_hostname }}_clos_spine_bgp_SP22_data_output.txt
  with_items: "{{clos_spine_bgp_SP22_data}}"
  
- name: Replace CLOS BGP Spine Switches CLI show template with values
  template: src=clos_spine_bgp_show.j2 dest=./commands/clos_spine_bgp_{{ inventory_hostname }}_show.txt
  with_items: "{{clos_spine_bgp_show}}"

- name: Applying CLI show commands CLOS BGP Spine Switches
  cnos_template: host={{ inventory_hostname }} username={{ hostvars[inventory_hostname]['username']}}  password={{ hostvars[inventory_hostname]['password']}} deviceType={{ hostvars[inventory_hostname]['deviceType']}} commandfile=./commands/clos_spine_bgp_{{ inventory_hostname }}_show.txt outputfile=./results/clos_spine_bgp_show_{{ inventory_hostname }}_output.txt
  with_items: "{{clos_spine_bgp_show}}"

# Completed file